version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/attack-search"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/attack-style"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      python-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
