version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/attack-search"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    cooldown:
      semver-major-days: 7
      semver-minor-days: 5
      semver-patch-days: 3
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/attack-style"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    cooldown:
      semver-major-days: 7
      semver-minor-days: 5
      semver-patch-days: 3
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    cooldown:
      semver-major-days: 7
      semver-minor-days: 5
      semver-patch-days: 3
    groups:
      python-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
