name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.58.0'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install python requirements
        run: python3 -m pip install -r requirements.txt

      - name: Get banner message
        run: echo "ATTACK_WEBSITE_BANNER_MESSAGE=$(<website-banner.production)" >> $GITHUB_ENV

      - name: Toggle banner if there is a message
        run: |
          if [[ -z "${ATTACK_WEBSITE_BANNER_MESSAGE}" ]]; then
            echo "ATTACK_WEBSITE_BANNER_ENABLED=false" >> $GITHUB_ENV
          else
            echo "ATTACK_WEBSITE_BANNER_ENABLED=true" >> $GITHUB_ENV
          fi

      - name: Build website
        run: >-
          just build-website --attack-brand
          --all-extras
          --no-test-exitstatus
        env:
          ATTACK_WEBSITE_GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
          ATTACK_WEBSITE_GOOGLE_SITE_VERIFICATION: ${{ secrets.GOOGLE_SITE_VERIFICATION }}
          ATTACK_WEBSITE_INCLUDE_OSANO: true
          PELICAN_SITEURL: https://attack.mitre.org

      - name: Cleanup build
        run: rm -rf attack-version-archives

      - name: Remove STIX directory
        run: rm -rf output/stix/

      - name: Add BlueSky Identification
        if: ${{ vars.BLUESKY_ID != '' }}
        run: |
          mkdir output/.well-known
          echo "${{ vars.BLUESKY_ID }}" > output/.well-known/atproto-did

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./output
          cname: attack.mitre.org
